name: Close jira ticket
author: Michael Ugochukwu
description: Closes a jira ticket associated with this PR upon merge
inputs:
  ticket_key:
    description: 'The link of the ticket'
    requried: True
  jira_user:
    description: The Jira user that will perform the action of closing the ticket
    required: True
  jira_url:
    description: The url to your jira ticket
    required: True
  jira_token:
    description: An auth token for the jira user
    required: True
runs:
  using: 'composite'
  steps:
    - name: "Setup env vars"
      run: |
        echo "JIRA_TICKET_KEY=${{inputs.ticket_key}}" >> $GITHUB_ENV
        echo "JIRA_URL=${{inputs.jira_url}}" >> $GITHUB_ENV
        echo "JIRA_USER=${{inputs.jira_user}}" >> $GITHUB_ENV
        echo "JIRA_TOKEN=${{inputs.jira_token}}" >> $GITHUB_ENV
      shell: bash
    - name: "Run python"
      run: "python ${{ github.action_path }}/main.py"
      shell: bash